### ISSUE TITLE
REQUEST: Discuss what is involved in compiling a GCC6-m68k release?

### ISSUE THREAD

**Issue by nyteshade** [bebbo/amiga-gcc#25]
## I know, I know, something to do with elf binaries

Curious what is involved in creating gcc for Amiga using this tool. Most folks are running GCC 2.95.3 on the actual hardware. Any chances we can use this to build a modern set of tools for the 68k? Especially with the Vampires in play.

**Comment by bebbo** [comment]
Make sure that I have more time for it :)

**Comment by nyteshade** [comment]
Heh. Of course. Maybe ideas on it could get done, some issues on what needs solving and then we could delegate to help provide more of that time.

**Comment by SamuraiCrow** [comment]
Firstly, what is the memory consumption of GCC 6.4?

**Comment by bebbo** [comment]
_ridiculous_ is the most precise answer

**Comment by SamuraiCrow** [comment]
Is it possible to make passes into external plugins so we can close the unused plugin libraries to free up RAM?

**Comment by bebbo** [comment]
```
  391048 Jul 22 22:37 addr2line
  391080 Jul 22 22:39 ar
  580392 Jul 22 23:26 as
  388040 Jul 22 22:37 c++filt
19865624 Jul 31 22:52 cc1
20666760 Jul 31 22:48 cc1obj
22421908 Jul 31 22:48 cc1plus
  877324 Jul 31 22:39 cpp
   42612 Jul 22 22:37 elfedit
  875824 Jul 31 22:39 gcc
  879468 Jul 31 22:39 g++
  437636 Jul 30 21:49 gcov-dump
  479236 Jul 30 21:49 gcov-tool
  459544 Jul 22 23:28 ld
  400448 Jul 22 22:37 nm
  501892 Jul 22 22:37 objcopy
  710300 Jul 22 22:37 objdump
  416284 Jul 22 22:37 ranlib
  504504 Jul 22 22:37 readelf
  392704 Jul 22 22:37 size
  391592 Jul 22 22:37 strings
  501896 Jul 22 22:37 strip
```
128MB RAM is not even start cc1
with 512MB it's starting but meets the guru.

**Comment by bebbo** [comment]
You have to run something like
```
CXX_FOR_BUILD=g++ CC_FOR_BUILD=gcc GCC_FOR_TARGET=m68k-amigaos-gcc CXXFLAGS="-Os -noixemul -fno-rtti -fno-exceptions" CFLAGS="-Os -noixemul" /absolute/path/to/gcc/configure --host=m68k-amigaos --prefix=/opt/amiga68 --enable-languages=c,c++,objc --enable-version-specific-runtime-libs --disable-libssp --disable-shared --disable-lto --disable-host-shared --disable-libstdcxx
make all-gcc
```
If build will hang because of -fPIC
* either modify the configure script to omit -fPIC
* or patch the created Makefile setting PICFLAG=

Last but no least you'll need proper implementations of
* dup
* dup2
* execv
* execvp
* fork
* kill
* pclose
* pipe
* popen
* wait
* waitpid

maybe some more.

good luck - I'm stopping here

**Comment by SamuraiCrow** [comment]
Fork would kill it indeed.

**Comment by bebbo** [comment]
I'm not sure if fork get's called, In pex-unix.c (which is part of libiberty) fork is placed into a function table. The function table is used from gcc/cc1* but maybe not fork.

I linked it using dummy functions :-)

the gcc frontend seems to work and cc1 is not working...
... since it's so sloooooooooow and requires 512MB (or more?)  I won't put more effort into it.

**Comment by SamuraiCrow** [comment]
Man, we better get you a Vampire v4 when it's out.  512 MiB Chip RAM and 68080 softcover on a Cyclone 5 FPGA.
