### ISSUE TITLE
Link Time Optimization not Working

### ISSUE THREAD

**Issue by RetroRevivalGames** [bebbo/amiga-gcc#295]
Hello,

I've been trying to get LTO to work with the amiga-gcc toolchain. However, when I add the -flto option, m68k-amigaos-gcc will not produce a binary. Otherwise the binary produces just fine. Is LTO supported by the m68k-amigaos toolchain?

![image](https://user-images.githubusercontent.com/87720313/178764301-cf0e4add-6a8d-478c-97b9-a7db3927d099.png)

Thank you!
RRGames

**Comment by githubaf** [comment]
Lto works with bebbos compiler.I have a separate linker call that also needs -fltoI use - noixemul.Von meinem/meiner Galaxy gesendet
-------- Ursprüngliche Nachricht --------Von: Matt Aguiar ***@***.***> Datum: 13.07.22  16:54  (GMT+01:00) An: bebbo/amiga-gcc ***@***.***> Cc: Subscribed ***@***.***> Betreff: [bebbo/amiga-gcc] Link Time Optimization not Working (Issue #295) 
Hello,
I've been trying to get LTO to work with the amiga-gcc toolchain. However, when I add the -flto option, m68k-amigaos-gcc will not produce a binary. Otherwise the binary produces just fine. Is LTO supported by the m68k-amigaos toolchain?

Thank you!
RRGames

**Comment by RetroRevivalGames** [comment]
Could you provide a quick sample of what you're talking about? What do you mean about a "separate linker call"?

Thanks.

**Comment by githubaf** [comment]
Something like m68k-amigaos-ld -noixemul app.o -o app -fltoVon meinem/meiner Galaxy gesendet
-------- Ursprüngliche Nachricht --------Von: Matt Aguiar ***@***.***> Datum: 13.07.22  17:16  (GMT+01:00) An: bebbo/amiga-gcc ***@***.***> Cc: githubaf ***@***.***>, Comment ***@***.***> Betreff: Re: [bebbo/amiga-gcc] Link Time Optimization not Working (Issue #295) 
Could you provide a quick sample of what you're talking about? What do you mean about a "separate linker call"?
Thanks.

**Comment by RetroRevivalGames** [comment]
Almost. Apologies, I am new to the amiga scene.

![image](https://user-images.githubusercontent.com/87720313/178774216-a65ef36a-c1ba-4ad3-a124-d2d819cc5ea8.png)

**Comment by githubaf** [comment]
Maybe without the fVon meinem/meiner Galaxy gesendet
-------- Ursprüngliche Nachricht --------Von: Matt Aguiar ***@***.***> Datum: 13.07.22  17:39  (GMT+01:00) An: bebbo/amiga-gcc ***@***.***> Cc: githubaf ***@***.***>, Comment ***@***.***> Betreff: Re: [bebbo/amiga-gcc] Link Time Optimization not Working (Issue #295) 
Almost. Apologies, I am new to the amiga scene.

**Comment by RetroRevivalGames** [comment]
No. That doesn't work. -flto is a gcc option, not a linker option.

**Comment by bebbo** [comment]
Guess this is one of the things that do not work on MSYS64. Since a while also the build of MSYS64 is broken...

Switch to WSL2 or WSL! Your command line will work there and create the executable.

**Comment by RetroRevivalGames** [comment]
You were right! It's just a problem with MSYS. Doing the same command on Cygwin works. Yes, I do have WSL as well. It's just that I'm using the toolchain for something that I want to support on different platforms like Windows, macOS and Linux. Thank you for the help.
