### ISSUE TITLE
error: ‘isl_val_free’ was not declared in this scope

### ISSUE THREAD

**Issue by felmur** [bebbo/amiga-gcc#341]
Hi,
when I compile, received this error:
_error: ‘isl_val_free’ was not declared in this scope; did you mean ‘isl_vec_free’?_
and this error:
_error: ‘isl_val_int_from_si’ was not declared in this scope; did you mean ‘isl_val_int_from_gmp’?_

I use Archlinux which have libisl version 0.26.
Please, see attached "make gcc.log" file.
Regards.
[make gcc.log](https://github.com/bebbo/amiga-gcc/files/11414957/make.gcc.log)

**Comment by bebbo** [comment]
downgrade isl to 0.18 - or use the gcc local version and run `contrib\download_prerequisites`

**Comment by felmur** [comment]
downgraded to libisl v0.18, it works.

**Comment by BrianHoldsworth** [comment]
I have the same issue building on Arch Linux. I cannot downgrade libisl because I have multiple other compilers that depend on the current version.

I did run the `contrib/download_prerequsites` script. It downloads some stuff, and that's about it, right? I see I have source code, presumably for libisl, in the `projects/gcc/isl` sub-directory. Do I need to build libisl from that directory and then install it somewhere on my system and somehow point the build process to that installed location?
